<a href="https://colab.research.google.com/github/Boedimennn/datamining/blob/main/SR1/DataMining_Modul_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from google.colab import files
from pandas.plotting import scatter_matrix
uploaded = files.upload()

file_path = list(uploaded.keys())[0]
data = pd.read_csv(file_path)

pd.set_option('display.width', 500)
pd.set_option('display.max_columns', 100)
pd.set_option('display.notebook_repr_html', True)
print(data.head())

Saving Eps2-Data-train.csv to Eps2-Data-train (2).csv
   PassengerId  Survived  Pclass                                               Name     Sex   Age  SibSp  Parch            Ticket     Fare Cabin Embarked
0            1         0       3                            Braund, Mr. Owen Harris    male  22.0      1      0         A/5 21171   7.2500   NaN        S
1            2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1      0          PC 17599  71.2833   C85        C
2            3         1       3                             Heikkinen, Miss. Laina  female  26.0      0      0  STON/O2. 3101282   7.9250   NaN        S
3            4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1      0            113803  53.1000  C123        S
4            5         0       3                           Allen, Mr. William Henry    male  35.0      0      0            373450   8.0500   NaN        S

In [ ]:
data = pd.DataFrame (data)
print (data.shape)

(891, 12)

In [ ]:
print (data.dtypes)

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [ ]:
print (data['Age'].dtypes)

float64

In [ ]:
data.describe()

       PassengerId    Survived      Pclass         Age       SibSp       Parch        Fare
count   891.000000  891.000000  891.000000  714.000000  891.000000  891.000000  891.000000
mean    446.000000    0.383838    2.308642   29.699118    0.523008    0.381594   32.204208
std     257.353842    0.486592    0.836071   14.526497    1.102743    0.806057   49.693429
min       1.000000    0.000000    1.000000    0.420000    0.000000    0.000000    0.000000
25%     223.500000    0.000000    2.000000   20.125000    0.000000    0.000000    7.910400
50%     446.000000    0.000000    3.000000   28.000000    0.000000    0.000000   14.454200
75%     668.500000    1.000000    3.000000   38.000000    1.000000    0.000000   31.000000
max     891.000000    1.000000    3.000000   80.000000    8.000000    6.000000  512.329200

In [ ]:
df = pd.DataFrame(data)
missing_values = df.isnull().sum()
print(missing_values)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df_cleaned = df.dropna()

In [ ]:
df['Age'].fillna(df['Age'].mean(), inplace=True)

In [ ]:
print(data)

     PassengerId  Survived  Pclass                                               Name     Sex        Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
0              1         0       3                            Braund, Mr. Owen Harris    male  22.000000      1      0           A/5 21171    7.2500              NaN        S
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000      1      0            PC 17599   71.2833              C85        C
2              3         1       3                             Heikkinen, Miss. Laina  female  26.000000      0      0    STON/O2. 3101282    7.9250              NaN        S
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000      1      0              113803   53.1000             C123        S
4              5         0       3                           Allen, Mr. William Henry    male  35.000000      0      0              373450    8.0500              NaN        S
5              6         0       3                                   Moran, Mr. James    male  29.699118      0      0              330877    8.4583              NaN        Q
6              7         0       1                            McCarthy, Mr. Timothy J    male  54.000000      0      0               17463   51.8625              E46        S
7              8         0       3                     Palsson, Master. Gosta Leonard    male   2.000000      3      1              349909   21.0750              NaN        S
8              9         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000      0      2              347742   11.1333              NaN        S
9             10         1       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000      1      0              237736   30.0708              NaN        C
10            11         1       3                    Sandstrom, Miss. Marguerite Rut  female   4.000000      1      1             PP 9549   16.7000               G6        S
11            12         1       1                           Bonnell, Miss. Elizabeth  female  58.000000      0      0              113783   26.5500             C103        S
12            13         0       3                     Saundercock, Mr. William Henry    male  20.000000      0      0           A/5. 2151    8.0500              NaN        S
13            14         0       3                        Andersson, Mr. Anders Johan    male  39.000000      1      5              347082   31.2750              NaN        S
14            15         0       3               Vestrom, Miss. Hulda Amanda Adolfina  female  14.000000      0      0              350406    7.8542              NaN        S
15            16         1       2                   Hewlett, Mrs. (Mary D Kingcome)   female  55.000000      0      0              248706   16.0000              NaN        S
16            17         0       3                               Rice, Master. Eugene    male   2.000000      4      1              382652   29.1250              NaN        Q
17            18         1       2                       Williams, Mr. Charles Eugene    male  29.699118      0      0              244373   13.0000              NaN        S
18            19         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.000000      1      0              345763   18.0000              NaN        S
19            20         1       3                            Masselmani, Mrs. Fatima  female  29.699118      0      0                2649    7.2250              NaN        C
20            21         0       2                               Fynney, Mr. Joseph J    male  35.000000      0      0              239865   26.0000              NaN        S
21            22         1       2                              Beesley, Mr. Lawrence    male  34.000000      0      0              248698   13.0000              D56        S
22            23         1       3                        McGowan, Miss. Anna "Annie"  female  15.000000      0      0              330923    8.0292              NaN        Q
23            24         1       1                       Sloper, Mr. William Thompson    male  28.000000      0      0              113788   35.5000               A6        S
24            25         0       3                      Palsson, Miss. Torborg Danira  female   8.000000      3      1              349909   21.0750              NaN        S
25            26         1       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.000000      1      5              347077   31.3875              NaN        S
26            27         0       3                            Emir, Mr. Farred Chehab    male  29.699118      0      0                2631    7.2250              NaN        C
27            28         0       1                     Fortune, Mr. Charles Alexander    male  19.000000      3      2               19950  263.0000      C23 C25 C27        S
28            29         1       3                      O'Dwyer, Miss. Ellen "Nellie"  female  29.699118      0      0              330959    7.8792              NaN        Q
29            30         0       3                                Todoroff, Mr. Lalio    male  29.699118      0      0              349216    7.8958              NaN        S
30            31         0       1                           Uruchurtu, Don. Manuel E    male  40.000000      0      0            PC 17601   27.7208              NaN        C
31            32         1       1     Spencer, Mrs. William Augustus (Marie Eugenie)  female  29.699118      1      0            PC 17569  146.5208              B78        C
32            33         1       3                           Glynn, Miss. Mary Agatha  female  29.699118      0      0              335677    7.7500              NaN        Q
33            34         0       2                              Wheadon, Mr. Edward H    male  66.000000      0      0          C.A. 24579   10.5000              NaN        S
34            35         0       1                            Meyer, Mr. Edgar Joseph    male  28.000000      1      0            PC 17604   82.1708              NaN        C
35            36         0       1                     Holverson, Mr. Alexander Oskar    male  42.000000      1      0              113789   52.0000              NaN        S
36            37         1       3                                   Mamee, Mr. Hanna    male  29.699118      0      0                2677    7.2292              NaN        C
37            38         0       3                           Cann, Mr. Ernest Charles    male  21.000000      0      0          A./5. 2152    8.0500              NaN        S
38            39         0       3                 Vander Planke, Miss. Augusta Maria  female  18.000000      2      0              345764   18.0000              NaN        S
39            40         1       3                        Nicola-Yarred, Miss. Jamila  female  14.000000      1      0                2651   11.2417              NaN        C
40            41         0       3     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.000000      1      0                7546    9.4750              NaN        S
41            42         0       2  Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.000000      1      0               11668   21.0000              NaN        S
42            43         0       3                                Kraeff, Mr. Theodor    male  29.699118      0      0              349253    7.8958              NaN        C
43            44         1       2           Laroche, Miss. Simonne Marie Anne Andree  female   3.000000      1      2       SC/Paris 2123   41.5792              NaN        C
44            45         1       3                      Devaney, Miss. Margaret Delia  female  19.000000      0      0              330958    7.8792              NaN        Q
45            46         0       3                           Rogers, Mr. William John    male  29.699118      0      0     S.C./A.4. 23567    8.0500              NaN        S
46            47         0       3                                  Lennon, Mr. Denis    male  29.699118      1      0              370371   15.5000              NaN        Q
47            48         1       3                          O'Driscoll, Miss. Bridget  female  29.699118      0      0               14311    7.7500              NaN        Q
48            49         0       3                                Samaan, Mr. Youssef    male  29.699118      2      0                2662   21.6792              NaN        C
49            50         0       3      Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.000000      1      0              349237   17.8000              NaN        S
50            51         0       3                         Panula, Master. Juha Niilo    male   7.000000      4      1             3101295   39.6875              NaN        S
51            52         0       3                       Nosworthy, Mr. Richard Cater    male  21.000000      0      0          A/4. 39886    7.8000              NaN        S
52            53         1       1           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.000000      1      0            PC 17572   76.7292              D33        C
53            54         1       2  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.000000      1      0                2926   26.0000              NaN        S
54            55         0       1                     Ostby, Mr. Engelhart Cornelius    male  65.000000      0      1              113509   61.9792              B30        C
55            56         1       1                                  Woolner, Mr. Hugh    male  29.699118      0      0               19947   35.5000              C52        S
56            57         1       2                                  Rugg, Miss. Emily  female  21.000000      0      0          C.A. 31026   10.5000              NaN        S
57            58         0       3                                Novel, Mr. Mansouer    male  28.500000      0      0                2697    7.2292              NaN        C
58            59         1       2                       West, Miss. Constance Mirium  female   5.000000      1      2          C.A. 34651   27.7500              NaN        S
59            60         0       3                 Goodwin, Master. William Frederick    male  11.000000      5      2             CA 2144   46.9000              NaN        S
60            61         0       3                              Sirayanian, Mr. Orsen    male  22.000000      0      0                2669    7.2292              NaN        C
61            62         1       1                                Icard, Miss. Amelie  female  38.000000      0      0              113572   80.0000              B28      NaN
62            63         0       1                        Harris, Mr. Henry Birkhardt    male  45.000000      1      0               36973   83.4750              C83        S
63            64         0       3                              Skoog, Master. Harald    male   4.000000      3      2              347088   27.9000              NaN        S
64            65         0       1                              Stewart, Mr. Albert A    male  29.699118      0      0            PC 17605   27.7208              NaN        C
65            66         1       3                           Moubarek, Master. Gerios    male  29.699118      1      1                2661   15.2458              NaN        C
66            67         1       2                       Nye, Mrs. (Elizabeth Ramell)  female  29.000000      0      0          C.A. 29395   10.5000              F33        S
67            68         0       3                           Crease, Mr. Ernest James    male  19.000000      0      0           S.P. 3464    8.1583              NaN        S
68            69         1       3                    Andersson, Miss. Erna Alexandra  female  17.000000      4      2             3101281    7.9250              NaN        S
69            70         0       3                                  Kink, Mr. Vincenz    male  26.000000      2      0              315151    8.6625              NaN        S
70            71         0       2                         Jenkin, Mr. Stephen Curnow    male  32.000000      0      0          C.A. 33111   10.5000              NaN        S
71            72         0       3                         Goodwin, Miss. Lillian Amy  female  16.000000      5      2             CA 2144   46.9000              NaN        S
72            73         0       2                               Hood, Mr. Ambrose Jr    male  21.000000      0      0        S.O.C. 14879   73.5000              NaN        S
73            74         0       3                        Chronopoulos, Mr. Apostolos    male  26.000000      1      0                2680   14.4542              NaN        C
74            75         1       3                                      Bing, Mr. Lee    male  32.000000      0      0                1601   56.4958              NaN        S
75            76         0       3                            Moen, Mr. Sigurd Hansen    male  25.000000      0      0              348123    7.6500            F G73        S
76            77         0       3                                  Staneff, Mr. Ivan    male  29.699118      0      0              349208    7.8958              NaN        S
77            78         0       3                           Moutal, Mr. Rahamin Haim    male  29.699118      0      0              374746    8.0500              NaN        S
78            79         1       2                      Caldwell, Master. Alden Gates    male   0.830000      0      2              248738   29.0000              NaN        S
79            80         1       3                           Dowdell, Miss. Elizabeth  female  30.000000      0      0              364516   12.4750              NaN        S
80            81         0       3                               Waelens, Mr. Achille    male  22.000000      0      0              345767    9.0000              NaN        S
81            82         1       3                        Sheerlinck, Mr. Jan Baptist    male  29.000000      0      0              345779    9.5000              NaN        S
82            83         1       3                     McDermott, Miss. Brigdet Delia  female  29.699118      0      0              330932    7.7875              NaN        Q
83            84         0       1                            Carrau, Mr. Francisco M    male  28.000000      0      0              113059   47.1000              NaN        S
84            85         1       2                                Ilett, Miss. Bertha  female  17.000000      0      0          SO/C 14885   10.5000              NaN        S
85            86         1       3  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female  33.000000      3      0             3101278   15.8500              NaN        S
86            87         0       3                             Ford, Mr. William Neal    male  16.000000      1      3          W./C. 6608   34.3750              NaN        S
87            88         0       3                      Slocovski, Mr. Selman Francis    male  29.699118      0      0     SOTON/OQ 392086    8.0500              NaN        S
88            89         1       1                         Fortune, Miss. Mabel Helen  female  23.000000      3      2               19950  263.0000      C23 C25 C27        S
89            90         0       3                             Celotti, Mr. Francesco    male  24.000000      0      0              343275    8.0500              NaN        S
90            91         0       3                               Christmann, Mr. Emil    male  29.000000      0      0              343276    8.0500              NaN        S
91            92         0       3                         Andreasson, Mr. Paul Edvin    male  20.000000      0      0              347466    7.8542              NaN        S
92            93         0       1                        Chaffee, Mr. Herbert Fuller    male  46.000000      1      0         W.E.P. 5734   61.1750              E31        S
93            94         0       3                            Dean, Mr. Bertram Frank    male  26.000000      1      2           C.A. 2315   20.5750              NaN        S
94            95         0       3                                  Coxon, Mr. Daniel    male  59.000000      0      0              364500    7.2500              NaN        S
95            96         0       3                        Shorney, Mr. Charles Joseph    male  29.699118      0      0              374910    8.0500              NaN        S
96            97         0       1                          Goldschmidt, Mr. George B    male  71.000000      0      0            PC 17754   34.6542               A5        C
97            98         1       1                    Greenfield, Mr. William Bertram    male  23.000000      0      1            PC 17759   63.3583          D10 D12        C
98            99         1       2               Doling, Mrs. John T (Ada Julia Bone)  female  34.000000      0      1              231919   23.0000              NaN        S
99           100         0       2                                  Kantor, Mr. Sinai    male  34.000000      1      0              244367   26.0000              NaN        S
100          101         0       3                            Petranec, Miss. Matilda  female  28.000000      0      0              349245    7.8958              NaN        S
101          102         0       3                   Petroff, Mr. Pastcho ("Pentcho")    male  29.699118      0      0              349215    7.8958              NaN        S
102          103         0       1                          White, Mr. Richard Frasar    male  21.000000      0      1               35281   77.2875              D26        S
103          104         0       3                         Johansson, Mr. Gustaf Joel    male  33.000000      0      0                7540    8.6542              NaN        S
104          105         0       3                     Gustafsson, Mr. Anders Vilhelm    male  37.000000      2      0             3101276    7.9250              NaN        S
105          106         0       3                              Mionoff, Mr. Stoytcho    male  28.000000      0      0              349207    7.8958              NaN        S
106          107         1       3                   Salkjelsvik, Miss. Anna Kristine  female  21.000000      0      0              343120    7.6500              NaN        S
107          108         1       3                             Moss, Mr. Albert Johan    male  29.699118      0      0              312991    7.7750              NaN        S
108          109         0       3                                    Rekic, Mr. Tido    male  38.000000      0      0              349249    7.8958              NaN        S
109          110         1       3                                Moran, Miss. Bertha  female  29.699118      1      0              371110   24.1500              NaN        Q
110          111         0       1                     Porter, Mr. Walter Chamberlain    male  47.000000      0      0              110465   52.0000             C110        S
111          112         0       3                               Zabour, Miss. Hileni  female  14.500000      1      0                2665   14.4542              NaN        C
112          113         0       3                             Barton, Mr. David John    male  22.000000      0      0              324669    8.0500              NaN        S

In [ ]:
print(data.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          891 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
None

In [ ]:
df = pd.DataFrame(data)
missing_values = df.isnull().sum()
print(missing_values)

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age              0
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
df['Cabin'].fillna('Unknown', inplace=True)

In [ ]:
df['Cabin'] = pd.to_numeric(df['Cabin'], errors='coerce')

In [ ]:
df['Cabin'].fillna(df['Cabin'].mean(), inplace=True)

In [ ]:
print(data)

     PassengerId  Survived  Pclass                                               Name     Sex        Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
0              1         0       3                            Braund, Mr. Owen Harris    male  22.000000      1      0           A/5 21171    7.2500          Unknown        S
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000      1      0            PC 17599   71.2833              C85        C
2              3         1       3                             Heikkinen, Miss. Laina  female  26.000000      0      0    STON/O2. 3101282    7.9250          Unknown        S
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000      1      0              113803   53.1000             C123        S
4              5         0       3                           Allen, Mr. William Henry    male  35.000000      0      0              373450    8.0500          Unknown        S
5              6         0       3                                   Moran, Mr. James    male  29.699118      0      0              330877    8.4583          Unknown        Q
6              7         0       1                            McCarthy, Mr. Timothy J    male  54.000000      0      0               17463   51.8625              E46        S
7              8         0       3                     Palsson, Master. Gosta Leonard    male   2.000000      3      1              349909   21.0750          Unknown        S
8              9         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000      0      2              347742   11.1333          Unknown        S
9             10         1       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000      1      0              237736   30.0708          Unknown        C
10            11         1       3                    Sandstrom, Miss. Marguerite Rut  female   4.000000      1      1             PP 9549   16.7000               G6        S
11            12         1       1                           Bonnell, Miss. Elizabeth  female  58.000000      0      0              113783   26.5500             C103        S
12            13         0       3                     Saundercock, Mr. William Henry    male  20.000000      0      0           A/5. 2151    8.0500          Unknown        S
13            14         0       3                        Andersson, Mr. Anders Johan    male  39.000000      1      5              347082   31.2750          Unknown        S
14            15         0       3               Vestrom, Miss. Hulda Amanda Adolfina  female  14.000000      0      0              350406    7.8542          Unknown        S
15            16         1       2                   Hewlett, Mrs. (Mary D Kingcome)   female  55.000000      0      0              248706   16.0000          Unknown        S
16            17         0       3                               Rice, Master. Eugene    male   2.000000      4      1              382652   29.1250          Unknown        Q
17            18         1       2                       Williams, Mr. Charles Eugene    male  29.699118      0      0              244373   13.0000          Unknown        S
18            19         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.000000      1      0              345763   18.0000          Unknown        S
19            20         1       3                            Masselmani, Mrs. Fatima  female  29.699118      0      0                2649    7.2250          Unknown        C
20            21         0       2                               Fynney, Mr. Joseph J    male  35.000000      0      0              239865   26.0000          Unknown        S
21            22         1       2                              Beesley, Mr. Lawrence    male  34.000000      0      0              248698   13.0000              D56        S
22            23         1       3                        McGowan, Miss. Anna "Annie"  female  15.000000      0      0              330923    8.0292          Unknown        Q
23            24         1       1                       Sloper, Mr. William Thompson    male  28.000000      0      0              113788   35.5000               A6        S
24            25         0       3                      Palsson, Miss. Torborg Danira  female   8.000000      3      1              349909   21.0750          Unknown        S
25            26         1       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.000000      1      5              347077   31.3875          Unknown        S
26            27         0       3                            Emir, Mr. Farred Chehab    male  29.699118      0      0                2631    7.2250          Unknown        C
27            28         0       1                     Fortune, Mr. Charles Alexander    male  19.000000      3      2               19950  263.0000      C23 C25 C27        S
28            29         1       3                      O'Dwyer, Miss. Ellen "Nellie"  female  29.699118      0      0              330959    7.8792          Unknown        Q
29            30         0       3                                Todoroff, Mr. Lalio    male  29.699118      0      0              349216    7.8958          Unknown        S
30            31         0       1                           Uruchurtu, Don. Manuel E    male  40.000000      0      0            PC 17601   27.7208          Unknown        C
31            32         1       1     Spencer, Mrs. William Augustus (Marie Eugenie)  female  29.699118      1      0            PC 17569  146.5208              B78        C
32            33         1       3                           Glynn, Miss. Mary Agatha  female  29.699118      0      0              335677    7.7500          Unknown        Q
33            34         0       2                              Wheadon, Mr. Edward H    male  66.000000      0      0          C.A. 24579   10.5000          Unknown        S
34            35         0       1                            Meyer, Mr. Edgar Joseph    male  28.000000      1      0            PC 17604   82.1708          Unknown        C
35            36         0       1                     Holverson, Mr. Alexander Oskar    male  42.000000      1      0              113789   52.0000          Unknown        S
36            37         1       3                                   Mamee, Mr. Hanna    male  29.699118      0      0                2677    7.2292          Unknown        C
37            38         0       3                           Cann, Mr. Ernest Charles    male  21.000000      0      0          A./5. 2152    8.0500          Unknown        S
38            39         0       3                 Vander Planke, Miss. Augusta Maria  female  18.000000      2      0              345764   18.0000          Unknown        S
39            40         1       3                        Nicola-Yarred, Miss. Jamila  female  14.000000      1      0                2651   11.2417          Unknown        C
40            41         0       3     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.000000      1      0                7546    9.4750          Unknown        S
41            42         0       2  Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.000000      1      0               11668   21.0000          Unknown        S
42            43         0       3                                Kraeff, Mr. Theodor    male  29.699118      0      0              349253    7.8958          Unknown        C
43            44         1       2           Laroche, Miss. Simonne Marie Anne Andree  female   3.000000      1      2       SC/Paris 2123   41.5792          Unknown        C
44            45         1       3                      Devaney, Miss. Margaret Delia  female  19.000000      0      0              330958    7.8792          Unknown        Q
45            46         0       3                           Rogers, Mr. William John    male  29.699118      0      0     S.C./A.4. 23567    8.0500          Unknown        S
46            47         0       3                                  Lennon, Mr. Denis    male  29.699118      1      0              370371   15.5000          Unknown        Q
47            48         1       3                          O'Driscoll, Miss. Bridget  female  29.699118      0      0               14311    7.7500          Unknown        Q
48            49         0       3                                Samaan, Mr. Youssef    male  29.699118      2      0                2662   21.6792          Unknown        C
49            50         0       3      Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.000000      1      0              349237   17.8000          Unknown        S
50            51         0       3                         Panula, Master. Juha Niilo    male   7.000000      4      1             3101295   39.6875          Unknown        S
51            52         0       3                       Nosworthy, Mr. Richard Cater    male  21.000000      0      0          A/4. 39886    7.8000          Unknown        S
52            53         1       1           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.000000      1      0            PC 17572   76.7292              D33        C
53            54         1       2  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.000000      1      0                2926   26.0000          Unknown        S
54            55         0       1                     Ostby, Mr. Engelhart Cornelius    male  65.000000      0      1              113509   61.9792              B30        C
55            56         1       1                                  Woolner, Mr. Hugh    male  29.699118      0      0               19947   35.5000              C52        S
56            57         1       2                                  Rugg, Miss. Emily  female  21.000000      0      0          C.A. 31026   10.5000          Unknown        S
57            58         0       3                                Novel, Mr. Mansouer    male  28.500000      0      0                2697    7.2292          Unknown        C
58            59         1       2                       West, Miss. Constance Mirium  female   5.000000      1      2          C.A. 34651   27.7500          Unknown        S
59            60         0       3                 Goodwin, Master. William Frederick    male  11.000000      5      2             CA 2144   46.9000          Unknown        S
60            61         0       3                              Sirayanian, Mr. Orsen    male  22.000000      0      0                2669    7.2292          Unknown        C
61            62         1       1                                Icard, Miss. Amelie  female  38.000000      0      0              113572   80.0000              B28      NaN
62            63         0       1                        Harris, Mr. Henry Birkhardt    male  45.000000      1      0               36973   83.4750              C83        S
63            64         0       3                              Skoog, Master. Harald    male   4.000000      3      2              347088   27.9000          Unknown        S
64            65         0       1                              Stewart, Mr. Albert A    male  29.699118      0      0            PC 17605   27.7208          Unknown        C
65            66         1       3                           Moubarek, Master. Gerios    male  29.699118      1      1                2661   15.2458          Unknown        C
66            67         1       2                       Nye, Mrs. (Elizabeth Ramell)  female  29.000000      0      0          C.A. 29395   10.5000              F33        S
67            68         0       3                           Crease, Mr. Ernest James    male  19.000000      0      0           S.P. 3464    8.1583          Unknown        S
68            69         1       3                    Andersson, Miss. Erna Alexandra  female  17.000000      4      2             3101281    7.9250          Unknown        S
69            70         0       3                                  Kink, Mr. Vincenz    male  26.000000      2      0              315151    8.6625          Unknown        S
70            71         0       2                         Jenkin, Mr. Stephen Curnow    male  32.000000      0      0          C.A. 33111   10.5000          Unknown        S
71            72         0       3                         Goodwin, Miss. Lillian Amy  female  16.000000      5      2             CA 2144   46.9000          Unknown        S
72            73         0       2                               Hood, Mr. Ambrose Jr    male  21.000000      0      0        S.O.C. 14879   73.5000          Unknown        S
73            74         0       3                        Chronopoulos, Mr. Apostolos    male  26.000000      1      0                2680   14.4542          Unknown        C
74            75         1       3                                      Bing, Mr. Lee    male  32.000000      0      0                1601   56.4958          Unknown        S
75            76         0       3                            Moen, Mr. Sigurd Hansen    male  25.000000      0      0              348123    7.6500            F G73        S
76            77         0       3                                  Staneff, Mr. Ivan    male  29.699118      0      0              349208    7.8958          Unknown        S
77            78         0       3                           Moutal, Mr. Rahamin Haim    male  29.699118      0      0              374746    8.0500          Unknown        S
78            79         1       2                      Caldwell, Master. Alden Gates    male   0.830000      0      2              248738   29.0000          Unknown        S
79            80         1       3                           Dowdell, Miss. Elizabeth  female  30.000000      0      0              364516   12.4750          Unknown        S
80            81         0       3                               Waelens, Mr. Achille    male  22.000000      0      0              345767    9.0000          Unknown        S
81            82         1       3                        Sheerlinck, Mr. Jan Baptist    male  29.000000      0      0              345779    9.5000          Unknown        S
82            83         1       3                     McDermott, Miss. Brigdet Delia  female  29.699118      0      0              330932    7.7875          Unknown        Q
83            84         0       1                            Carrau, Mr. Francisco M    male  28.000000      0      0              113059   47.1000          Unknown        S
84            85         1       2                                Ilett, Miss. Bertha  female  17.000000      0      0          SO/C 14885   10.5000          Unknown        S
85            86         1       3  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female  33.000000      3      0             3101278   15.8500          Unknown        S
86            87         0       3                             Ford, Mr. William Neal    male  16.000000      1      3          W./C. 6608   34.3750          Unknown        S
87            88         0       3                      Slocovski, Mr. Selman Francis    male  29.699118      0      0     SOTON/OQ 392086    8.0500          Unknown        S
88            89         1       1                         Fortune, Miss. Mabel Helen  female  23.000000      3      2               19950  263.0000      C23 C25 C27        S
89            90         0       3                             Celotti, Mr. Francesco    male  24.000000      0      0              343275    8.0500          Unknown        S
90            91         0       3                               Christmann, Mr. Emil    male  29.000000      0      0              343276    8.0500          Unknown        S
91            92         0       3                         Andreasson, Mr. Paul Edvin    male  20.000000      0      0              347466    7.8542          Unknown        S
92            93         0       1                        Chaffee, Mr. Herbert Fuller    male  46.000000      1      0         W.E.P. 5734   61.1750              E31        S
93            94         0       3                            Dean, Mr. Bertram Frank    male  26.000000      1      2           C.A. 2315   20.5750          Unknown        S
94            95         0       3                                  Coxon, Mr. Daniel    male  59.000000      0      0              364500    7.2500          Unknown        S
95            96         0       3                        Shorney, Mr. Charles Joseph    male  29.699118      0      0              374910    8.0500          Unknown        S
96            97         0       1                          Goldschmidt, Mr. George B    male  71.000000      0      0            PC 17754   34.6542               A5        C
97            98         1       1                    Greenfield, Mr. William Bertram    male  23.000000      0      1            PC 17759   63.3583          D10 D12        C
98            99         1       2               Doling, Mrs. John T (Ada Julia Bone)  female  34.000000      0      1              231919   23.0000          Unknown        S
99           100         0       2                                  Kantor, Mr. Sinai    male  34.000000      1      0              244367   26.0000          Unknown        S
100          101         0       3                            Petranec, Miss. Matilda  female  28.000000      0      0              349245    7.8958          Unknown        S
101          102         0       3                   Petroff, Mr. Pastcho ("Pentcho")    male  29.699118      0      0              349215    7.8958          Unknown        S
102          103         0       1                          White, Mr. Richard Frasar    male  21.000000      0      1               35281   77.2875              D26        S
103          104         0       3                         Johansson, Mr. Gustaf Joel    male  33.000000      0      0                7540    8.6542          Unknown        S
104          105         0       3                     Gustafsson, Mr. Anders Vilhelm    male  37.000000      2      0             3101276    7.9250          Unknown        S
105          106         0       3                              Mionoff, Mr. Stoytcho    male  28.000000      0      0              349207    7.8958          Unknown        S
106          107         1       3                   Salkjelsvik, Miss. Anna Kristine  female  21.000000      0      0              343120    7.6500          Unknown        S
107          108         1       3                             Moss, Mr. Albert Johan    male  29.699118      0      0              312991    7.7750          Unknown        S
108          109         0       3                                    Rekic, Mr. Tido    male  38.000000      0      0              349249    7.8958          Unknown        S
109          110         1       3                                Moran, Miss. Bertha  female  29.699118      1      0              371110   24.1500          Unknown        Q
110          111         0       1                     Porter, Mr. Walter Chamberlain    male  47.000000      0      0              110465   52.0000             C110        S
111          112         0       3                               Zabour, Miss. Hileni  female  14.500000      1      0                2665   14.4542          Unknown        C
112          113         0       3                             Barton, Mr. David John    male  22.000000      0      0              324669    8.0500          Unknown        S

In [ ]:
df = pd.DataFrame(data)
missing_values = df.isnull().sum()
print(missing_values)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       2
dtype: int64

In [ ]:
df['Embarked'].fillna('Unknown', inplace=True)

In [ ]:
df['Embarked'] = pd.to_numeric(df['Embarked'], errors='coerce')

In [ ]:
df['Embarked'].fillna(df['Embarked'].mean(), inplace=True)

In [ ]:
df = pd.DataFrame(data)
missing_values = df.isnull().sum()
print(missing_values)

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
print(df.columns)

Index(['passengerid', 'survived', 'pclass', 'name', 'sex', 'age', 'sibsp', 'parch', 'ticket', 'fare', 'cabin', 'embarked'], dtype='object')

In [ ]:
df.drop(columns=['A'], inplace=True, errors='ignore')

In [ ]:
print(data)

     PassengerId  Survived  Pclass                                               Name     Sex        Age  SibSp  Parch              Ticket      Fare            Cabin Embarked
0              1         0       3                            Braund, Mr. Owen Harris    male  22.000000      1      0           A/5 21171    7.2500          Unknown        S
1              2         1       1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.000000      1      0            PC 17599   71.2833              C85        C
2              3         1       3                             Heikkinen, Miss. Laina  female  26.000000      0      0    STON/O2. 3101282    7.9250          Unknown        S
3              4         1       1       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.000000      1      0              113803   53.1000             C123        S
4              5         0       3                           Allen, Mr. William Henry    male  35.000000      0      0              373450    8.0500          Unknown        S
5              6         0       3                                   Moran, Mr. James    male  29.699118      0      0              330877    8.4583          Unknown        Q
6              7         0       1                            McCarthy, Mr. Timothy J    male  54.000000      0      0               17463   51.8625              E46        S
7              8         0       3                     Palsson, Master. Gosta Leonard    male   2.000000      3      1              349909   21.0750          Unknown        S
8              9         1       3  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.000000      0      2              347742   11.1333          Unknown        S
9             10         1       2                Nasser, Mrs. Nicholas (Adele Achem)  female  14.000000      1      0              237736   30.0708          Unknown        C
10            11         1       3                    Sandstrom, Miss. Marguerite Rut  female   4.000000      1      1             PP 9549   16.7000               G6        S
11            12         1       1                           Bonnell, Miss. Elizabeth  female  58.000000      0      0              113783   26.5500             C103        S
12            13         0       3                     Saundercock, Mr. William Henry    male  20.000000      0      0           A/5. 2151    8.0500          Unknown        S
13            14         0       3                        Andersson, Mr. Anders Johan    male  39.000000      1      5              347082   31.2750          Unknown        S
14            15         0       3               Vestrom, Miss. Hulda Amanda Adolfina  female  14.000000      0      0              350406    7.8542          Unknown        S
15            16         1       2                   Hewlett, Mrs. (Mary D Kingcome)   female  55.000000      0      0              248706   16.0000          Unknown        S
16            17         0       3                               Rice, Master. Eugene    male   2.000000      4      1              382652   29.1250          Unknown        Q
17            18         1       2                       Williams, Mr. Charles Eugene    male  29.699118      0      0              244373   13.0000          Unknown        S
18            19         0       3  Vander Planke, Mrs. Julius (Emelia Maria Vande...  female  31.000000      1      0              345763   18.0000          Unknown        S
19            20         1       3                            Masselmani, Mrs. Fatima  female  29.699118      0      0                2649    7.2250          Unknown        C
20            21         0       2                               Fynney, Mr. Joseph J    male  35.000000      0      0              239865   26.0000          Unknown        S
21            22         1       2                              Beesley, Mr. Lawrence    male  34.000000      0      0              248698   13.0000              D56        S
22            23         1       3                        McGowan, Miss. Anna "Annie"  female  15.000000      0      0              330923    8.0292          Unknown        Q
23            24         1       1                       Sloper, Mr. William Thompson    male  28.000000      0      0              113788   35.5000               A6        S
24            25         0       3                      Palsson, Miss. Torborg Danira  female   8.000000      3      1              349909   21.0750          Unknown        S
25            26         1       3  Asplund, Mrs. Carl Oscar (Selma Augusta Emilia...  female  38.000000      1      5              347077   31.3875          Unknown        S
26            27         0       3                            Emir, Mr. Farred Chehab    male  29.699118      0      0                2631    7.2250          Unknown        C
27            28         0       1                     Fortune, Mr. Charles Alexander    male  19.000000      3      2               19950  263.0000      C23 C25 C27        S
28            29         1       3                      O'Dwyer, Miss. Ellen "Nellie"  female  29.699118      0      0              330959    7.8792          Unknown        Q
29            30         0       3                                Todoroff, Mr. Lalio    male  29.699118      0      0              349216    7.8958          Unknown        S
30            31         0       1                           Uruchurtu, Don. Manuel E    male  40.000000      0      0            PC 17601   27.7208          Unknown        C
31            32         1       1     Spencer, Mrs. William Augustus (Marie Eugenie)  female  29.699118      1      0            PC 17569  146.5208              B78        C
32            33         1       3                           Glynn, Miss. Mary Agatha  female  29.699118      0      0              335677    7.7500          Unknown        Q
33            34         0       2                              Wheadon, Mr. Edward H    male  66.000000      0      0          C.A. 24579   10.5000          Unknown        S
34            35         0       1                            Meyer, Mr. Edgar Joseph    male  28.000000      1      0            PC 17604   82.1708          Unknown        C
35            36         0       1                     Holverson, Mr. Alexander Oskar    male  42.000000      1      0              113789   52.0000          Unknown        S
36            37         1       3                                   Mamee, Mr. Hanna    male  29.699118      0      0                2677    7.2292          Unknown        C
37            38         0       3                           Cann, Mr. Ernest Charles    male  21.000000      0      0          A./5. 2152    8.0500          Unknown        S
38            39         0       3                 Vander Planke, Miss. Augusta Maria  female  18.000000      2      0              345764   18.0000          Unknown        S
39            40         1       3                        Nicola-Yarred, Miss. Jamila  female  14.000000      1      0                2651   11.2417          Unknown        C
40            41         0       3     Ahlin, Mrs. Johan (Johanna Persdotter Larsson)  female  40.000000      1      0                7546    9.4750          Unknown        S
41            42         0       2  Turpin, Mrs. William John Robert (Dorothy Ann ...  female  27.000000      1      0               11668   21.0000          Unknown        S
42            43         0       3                                Kraeff, Mr. Theodor    male  29.699118      0      0              349253    7.8958          Unknown        C
43            44         1       2           Laroche, Miss. Simonne Marie Anne Andree  female   3.000000      1      2       SC/Paris 2123   41.5792          Unknown        C
44            45         1       3                      Devaney, Miss. Margaret Delia  female  19.000000      0      0              330958    7.8792          Unknown        Q
45            46         0       3                           Rogers, Mr. William John    male  29.699118      0      0     S.C./A.4. 23567    8.0500          Unknown        S
46            47         0       3                                  Lennon, Mr. Denis    male  29.699118      1      0              370371   15.5000          Unknown        Q
47            48         1       3                          O'Driscoll, Miss. Bridget  female  29.699118      0      0               14311    7.7500          Unknown        Q
48            49         0       3                                Samaan, Mr. Youssef    male  29.699118      2      0                2662   21.6792          Unknown        C
49            50         0       3      Arnold-Franchi, Mrs. Josef (Josefine Franchi)  female  18.000000      1      0              349237   17.8000          Unknown        S
50            51         0       3                         Panula, Master. Juha Niilo    male   7.000000      4      1             3101295   39.6875          Unknown        S
51            52         0       3                       Nosworthy, Mr. Richard Cater    male  21.000000      0      0          A/4. 39886    7.8000          Unknown        S
52            53         1       1           Harper, Mrs. Henry Sleeper (Myna Haxtun)  female  49.000000      1      0            PC 17572   76.7292              D33        C
53            54         1       2  Faunthorpe, Mrs. Lizzie (Elizabeth Anne Wilkin...  female  29.000000      1      0                2926   26.0000          Unknown        S
54            55         0       1                     Ostby, Mr. Engelhart Cornelius    male  65.000000      0      1              113509   61.9792              B30        C
55            56         1       1                                  Woolner, Mr. Hugh    male  29.699118      0      0               19947   35.5000              C52        S
56            57         1       2                                  Rugg, Miss. Emily  female  21.000000      0      0          C.A. 31026   10.5000          Unknown        S
57            58         0       3                                Novel, Mr. Mansouer    male  28.500000      0      0                2697    7.2292          Unknown        C
58            59         1       2                       West, Miss. Constance Mirium  female   5.000000      1      2          C.A. 34651   27.7500          Unknown        S
59            60         0       3                 Goodwin, Master. William Frederick    male  11.000000      5      2             CA 2144   46.9000          Unknown        S
60            61         0       3                              Sirayanian, Mr. Orsen    male  22.000000      0      0                2669    7.2292          Unknown        C
61            62         1       1                                Icard, Miss. Amelie  female  38.000000      0      0              113572   80.0000              B28  Unknown
62            63         0       1                        Harris, Mr. Henry Birkhardt    male  45.000000      1      0               36973   83.4750              C83        S
63            64         0       3                              Skoog, Master. Harald    male   4.000000      3      2              347088   27.9000          Unknown        S
64            65         0       1                              Stewart, Mr. Albert A    male  29.699118      0      0            PC 17605   27.7208          Unknown        C
65            66         1       3                           Moubarek, Master. Gerios    male  29.699118      1      1                2661   15.2458          Unknown        C
66            67         1       2                       Nye, Mrs. (Elizabeth Ramell)  female  29.000000      0      0          C.A. 29395   10.5000              F33        S
67            68         0       3                           Crease, Mr. Ernest James    male  19.000000      0      0           S.P. 3464    8.1583          Unknown        S
68            69         1       3                    Andersson, Miss. Erna Alexandra  female  17.000000      4      2             3101281    7.9250          Unknown        S
69            70         0       3                                  Kink, Mr. Vincenz    male  26.000000      2      0              315151    8.6625          Unknown        S
70            71         0       2                         Jenkin, Mr. Stephen Curnow    male  32.000000      0      0          C.A. 33111   10.5000          Unknown        S
71            72         0       3                         Goodwin, Miss. Lillian Amy  female  16.000000      5      2             CA 2144   46.9000          Unknown        S
72            73         0       2                               Hood, Mr. Ambrose Jr    male  21.000000      0      0        S.O.C. 14879   73.5000          Unknown        S
73            74         0       3                        Chronopoulos, Mr. Apostolos    male  26.000000      1      0                2680   14.4542          Unknown        C
74            75         1       3                                      Bing, Mr. Lee    male  32.000000      0      0                1601   56.4958          Unknown        S
75            76         0       3                            Moen, Mr. Sigurd Hansen    male  25.000000      0      0              348123    7.6500            F G73        S
76            77         0       3                                  Staneff, Mr. Ivan    male  29.699118      0      0              349208    7.8958          Unknown        S
77            78         0       3                           Moutal, Mr. Rahamin Haim    male  29.699118      0      0              374746    8.0500          Unknown        S
78            79         1       2                      Caldwell, Master. Alden Gates    male   0.830000      0      2              248738   29.0000          Unknown        S
79            80         1       3                           Dowdell, Miss. Elizabeth  female  30.000000      0      0              364516   12.4750          Unknown        S
80            81         0       3                               Waelens, Mr. Achille    male  22.000000      0      0              345767    9.0000          Unknown        S
81            82         1       3                        Sheerlinck, Mr. Jan Baptist    male  29.000000      0      0              345779    9.5000          Unknown        S
82            83         1       3                     McDermott, Miss. Brigdet Delia  female  29.699118      0      0              330932    7.7875          Unknown        Q
83            84         0       1                            Carrau, Mr. Francisco M    male  28.000000      0      0              113059   47.1000          Unknown        S
84            85         1       2                                Ilett, Miss. Bertha  female  17.000000      0      0          SO/C 14885   10.5000          Unknown        S
85            86         1       3  Backstrom, Mrs. Karl Alfred (Maria Mathilda Gu...  female  33.000000      3      0             3101278   15.8500          Unknown        S
86            87         0       3                             Ford, Mr. William Neal    male  16.000000      1      3          W./C. 6608   34.3750          Unknown        S
87            88         0       3                      Slocovski, Mr. Selman Francis    male  29.699118      0      0     SOTON/OQ 392086    8.0500          Unknown        S
88            89         1       1                         Fortune, Miss. Mabel Helen  female  23.000000      3      2               19950  263.0000      C23 C25 C27        S
89            90         0       3                             Celotti, Mr. Francesco    male  24.000000      0      0              343275    8.0500          Unknown        S
90            91         0       3                               Christmann, Mr. Emil    male  29.000000      0      0              343276    8.0500          Unknown        S
91            92         0       3                         Andreasson, Mr. Paul Edvin    male  20.000000      0      0              347466    7.8542          Unknown        S
92            93         0       1                        Chaffee, Mr. Herbert Fuller    male  46.000000      1      0         W.E.P. 5734   61.1750              E31        S
93            94         0       3                            Dean, Mr. Bertram Frank    male  26.000000      1      2           C.A. 2315   20.5750          Unknown        S
94            95         0       3                                  Coxon, Mr. Daniel    male  59.000000      0      0              364500    7.2500          Unknown        S
95            96         0       3                        Shorney, Mr. Charles Joseph    male  29.699118      0      0              374910    8.0500          Unknown        S
96            97         0       1                          Goldschmidt, Mr. George B    male  71.000000      0      0            PC 17754   34.6542               A5        C
97            98         1       1                    Greenfield, Mr. William Bertram    male  23.000000      0      1            PC 17759   63.3583          D10 D12        C
98            99         1       2               Doling, Mrs. John T (Ada Julia Bone)  female  34.000000      0      1              231919   23.0000          Unknown        S
99           100         0       2                                  Kantor, Mr. Sinai    male  34.000000      1      0              244367   26.0000          Unknown        S
100          101         0       3                            Petranec, Miss. Matilda  female  28.000000      0      0              349245    7.8958          Unknown        S
101          102         0       3                   Petroff, Mr. Pastcho ("Pentcho")    male  29.699118      0      0              349215    7.8958          Unknown        S
102          103         0       1                          White, Mr. Richard Frasar    male  21.000000      0      1               35281   77.2875              D26        S
103          104         0       3                         Johansson, Mr. Gustaf Joel    male  33.000000      0      0                7540    8.6542          Unknown        S
104          105         0       3                     Gustafsson, Mr. Anders Vilhelm    male  37.000000      2      0             3101276    7.9250          Unknown        S
105          106         0       3                              Mionoff, Mr. Stoytcho    male  28.000000      0      0              349207    7.8958          Unknown        S
106          107         1       3                   Salkjelsvik, Miss. Anna Kristine  female  21.000000      0      0              343120    7.6500          Unknown        S
107          108         1       3                             Moss, Mr. Albert Johan    male  29.699118      0      0              312991    7.7750          Unknown        S
108          109         0       3                                    Rekic, Mr. Tido    male  38.000000      0      0              349249    7.8958          Unknown        S
109          110         1       3                                Moran, Miss. Bertha  female  29.699118      1      0              371110   24.1500          Unknown        Q
110          111         0       1                     Porter, Mr. Walter Chamberlain    male  47.000000      0      0              110465   52.0000             C110        S
111          112         0       3                               Zabour, Miss. Hileni  female  14.500000      1      0                2665   14.4542          Unknown        C
112          113         0       3                             Barton, Mr. David John    male  22.000000      0      0              324669    8.0500          Unknown        S

In [ ]:
data.to_csv('hasil_cleaning_modul1.csv')

files.download('hasil_cleaning_modul1.csv')